### ISSUE TITLE
Issues?

### ISSUE THREAD

**Issue by agucova** [essandess/macOS-Fortress#1]
So, I runned the script, and the last lines where...
`/System/Library/LaunchDaemons/org.apache.httpd.plist: service already loaded
missing header for unified diff at line 3 of patch
patching file /opt/local/etc/squid/squid.conf
missing header for unified diff at line 3 of patch
patching file /opt/local/etc/privoxy/config
install: /opt/local/etc/privoxy/match.all: No such file or directory
/usr/bin/diff: /opt/local/etc/privoxy/match.all: No such file or directory
/usr/bin/diff: ./match.all: No such file or directory
missing header for unified diff at line 3 of patch
patching file /opt/local/etc/privoxy/user.action
cp: /etc/hosts: No such file or directory
install: ./privoxy-adblock/privoxy-adblock.sh: No such file or directory
/Users/ForgottenPlayer/Library/LaunchAgents/org.opensource.flashcookiedelete.plist: Service is disabled`

And right now, I don't know how I could test, if the proxy is working... When visiting "localhost/proxy.pac", it gives connection refused, so I configured the "Automatic Proxy Config" to "/Users/ForgottenPlayer/osxfortress/proxy.pac" 
When I set the proxy settings to port 8118, privoxy works, I can visit p.p, but when I change it to 3128, I get "ERR_PROXY_CONNECTION_FAILED"

Right know, I don't know what is failing... (Or working)

**Comment by essandess** [comment]
It looks like there are issues with Apache on your box. Here are some troubleshooting hints:
- Test to make sure Apache is running properly:
  - `sudo apachectl stop && sudo apachectl start`
  - Browse to http://127.0.0.1/  and see if you see the test homepage.
- If Apache isn't working on your OS X, fix it. Google errors, see apple discussions.
- If it is working, copy a proxy.pac file to your /Library/WebServer directory and make sure you can browse to http://127.0.0.1/proxy.pac
- These commands will tell you if squid and privoxy are up and running and bound to their default ports:
  - `sudo lsof -i ':3128'`
  - `sudo lsof -i ':8118'`

**Comment by RaDeleon** [comment]
Thanks for reviving this project!

**Comment by essandess** [comment]
Looks like a local issue with Apache, unrelated to repo.
