### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by ngerasimatos** [essandess/macOS-Fortress#10]
$ cat opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_stack/stack/main.log | grep -i fail

:debug:archivefetch Fetching archive failed: The requested URL returned error: 404 Not Found
:debug:archivefetch Fetching archive failed: The requested URL returned error: 404 Not Found
:debug:archivefetch Fetching archive failed: The requested URL returned error: 404 Not Found
:info:build base-compat           > [  9 of 112] Compiling Control.Monad.Fail.Compat
:info:build base-compat           > [ 10 of 112] Compiling Control.Monad.Fail.Compat.Repl
:info:build Cabal                 > [  5 of 234] Compiling Distribution.Compat.MonadFail
:info:build aeson                 > 800 | withBoundedScientific_ whenFail f v@(Number scientific) =
:info:build aeson-compat          > 119 | import           Data.Aeson.Types (Parser, modifyFailure, typeMismatch, defaultOptions)
:info:build mustache              >     Deprecated: "Please use decodeEither' or decodeThrow, which provide more useful failures"
:info:build     Process exited with code: ExitFailure 1
:info:build Command failed:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_stack/stack/work/stack-2.5.1" && /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_stack/stack/work/bin/stack build --with-gcc /usr/bin/clang --allow-different-user 
:error:build Failed to build stack: command execution failed
:debug:build Backtrace: command execution failed
:debug:archivefetch Fetching archive failed: The requested URL returned error: 404 Not Found
:debug:archivefetch Fetching archive failed: The requested URL returned error: 404 Not Found
:debug:archivefetch Fetching archive failed: The requested URL returned error: 404 Not Found
:info:build     Process exited with code: ExitFailure 1
:info:build Command failed:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_stack/stack/work/stack-2.5.1" && /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_stack/stack/work/bin/stack build --with-gcc /usr/bin/clang --allow-different-user 
:error:build Failed to build stack: command execution failed
:debug:build Backtrace: command execution failed

**Comment by rom3r4** [comment]
I am getting that exact same error when installing on macOS Big Sur

Attached is my log file

[main.log](https://github.com/essandess/macOS-Fortress/files/5794918/main.log)

**Comment by essandess** [comment]
There’s been a bunch of updates at MacPorts upstream, including `stack` on which your log shows the fail. Would you please try again? Also, this would count as a MacPorts issue now, so please post issues at https://trac.macports.org/.

I’m going to close this issue because it belongs at MacPorts, not this deprecated repo.
