### ISSUE TITLE
p.p

### ISSUE THREAD

**Issue by agucova** [essandess/macOS-Fortress#2]
Hello, so after my latest issue, I fixed my apache configuration (by basically, resetting everything).
My proxy.pac is is working, I have set up the automatic proxy config, based on "127.0.0.1/proxy.pac"
Now, I cannot access p.p.
I was wondering, how I can test everything is working?
PD: Both privoxy & squid, seem to be running
PD2: If I set manually the http proxy to 3128, it seems on squid's access.log, that is working, but after some correct results, it starts to make weird TCP_MISS_ABORTED, and doesn't let me into webpages, or only few.

**Comment by essandess** [comment]
What are the results of these troubleshooting steps?
- Test to make sure Apache is running properly:
  - `sudo apachectl stop && sudo apachectl start`
  - Browse to http://127.0.0.1/  and see if you see the test homepage.
- If Apache isn't working on your OS X, fix it. Google errors, see apple discussions.
- If it is working, copy a proxy.pac file to your /Library/WebServer directory and make sure you can browse to http://127.0.0.1/proxy.pac
- These commands will tell you if squid and privoxy are up and running and bound to their default ports:
  - `sudo lsof -i ':3128'`
  - `sudo lsof -i ':8118'`
- Look for the running processes:
  - `ps -ef | grep squid`
  - `ps -ef | grep privoxy`
- Manually set the proxy to privoxy only, `127.0.0.1:8118`, and browse to http://p.p.
- Manually set the proxy to squid:privoxy, `127.0.0.1:3128`, and browse to http://p.p.
- Scan access and error logs in `/opt/local/var/…`

**Comment by agucova** [comment]
Again, github is not notificating me of replies, even with suscribe.

**Comment by agucova** [comment]
I can go to 127.0.0.1/proxy.pac, and shows perfectly.
Squid is running and bond to 3128.
It seems that privoxy doesn't run on boot, I need to initiate it manually, but I have the LaunchService, active. 
Is there a way I can uninstall any changes made by osxfortress? (I want a clean install)

**Comment by agucova** [comment]
The launchservice runs `/usr/local/sbin/privoxy /usr/local/etc/privoxy/config`
But privoxy is installed on `/opt/local/sbin/privoxy`
That's why its not starting. I changed it to the correct path, now it works.

**Comment by agucova** [comment]
After starting privoxy manually, and setting the proxy to privoxy (8118), I can see privoxy working perfectly. (and my internet)
When setting it to, squid (3128), it starts to make the same weird TCP_MISS_ABORTED (according to the log), to almost all of the requests. And doesn't show p.p.

**Comment by essandess** [comment]
That all sound strange. Are you using Macports or Brew to install privoxy and squid? Macports puts everything in `/opt/local`, and `sudo port load privoxy` creates a launch daemon that points there.

Don't think of osxfortress as an app to install/uninstall, but simply a secure, privatizing configuration for proxy services you install through a package manager.

**Comment by essandess** [comment]
Sounds like possibly a Macports/brew install conflict. Just choose one package manager.
