### ISSUE TITLE
Issues with easylist.script.*

### ISSUE THREAD

**Issue by malaeum** [essandess/macOS-Fortress#4]
Hello and first of all let me say thank you for your work on this project.

I've been trying to get this up and running and have hit a snag. I've run the installer, but it seems I am having some issues getting privoxy online. Based on the previous issues I have confirmed that it is not running (lsof -i ':8118' returns nothing, ps -ef | grep privoxy returns the query itself). Attempting to start it manually returns nothing, but no process running; manually starting it with --no-daemon however seems to finally shed some light on what is happening:

`2017-04-05 18:24:34.991 7fffb076c Info: Privoxy version 3.0.26
2017-04-05 18:24:34.991 7fffb076c Info: Program name: /opt/local/sbin/privoxy
2017-04-05 18:24:34.998 7fffb076c Fatal error: can't load re_filterfile '/opt/local/etc/privoxy/easylist.script.filter': No such file or directory`

For some reason in the extracted osxfortress-master folder I see nothing within the privoxy-adblock directory, so from GitHub I grab the shell script and run it. There is a typo on line 114 (the call for $sedcmd is missing the final d), once corrected I still get a small error while starting privoxy:

`2017-04-05 18:27:33.388 7fffb076c Fatal error: can't load actions file '/opt/local/etc/privoxy/easylist.script.action': line 1 should begin with a '{': -e { +block{easylist} }`

A quick google search for an example of the file more or less shows the same contents just without the leading -e so I manually edited it and that seems to resolve things (I won't even pretend to understand the syntax of sed, but it seems that there might be a small issue with the command that adds the leading -e). In any case, privoxy now seems to start (lsof and ps both list it) however I am still unable to access it by trying to visit the p.p page. I've tried it both with and without the "Automatic Proxy Configuration" option enabled on my network connection, though I don't think that that would make much of a difference. I am sort stuck here and not sure where to proceed next now that it seems to be running, maybe possibly. 

I'll be the first to admit that I am not exactly a proficient coder, though I think I am able to follow along with a process fairly well (see debugging, at least of typos, done above). Maybe there is something that I'm missing and I'll end up in a much better place after a /facepalm moment.

**Comment by essandess** [comment]
There are correctness issues with the `privoxy-adblock` blocking rules. See [here](../../../../skroll/privoxy-adblock/issues/11).

I've recently created a new repo [easylist-pac-privoxy](../../easylist-pac-privoxy) that addresses all these issues, and provides much more comprehensive network-level tracker and ad blocking with EasyList rules, complete with element hiding.

I'm working to incorporate this with automated updates and will refactor all this into this repo soon(ish).

It will completely replace `privoxy-adblock` and the existing `proxy.pac` setup. I'll comment after I add this capability.

**Comment by essandess** [comment]
I've committed an upgrade to the [easylist-pac-privoxy](../../../essandess/easylist-pac-privoxy/) repo, and deprecated the approach mentioned in this issue.

Please see the [readme-and-install.sh](../../../essandess/osxfortress/blob/master/readme-and-install.sh) for commands to install and use the new converters.
