### ISSUE TITLE
Installation needs several manual fixes

### ISSUE THREAD

**Issue by noyannus** [essandess/macOS-Fortress#7]
Trying to install on a clean-ish system[*] I met several issues that needed a manual fix. 

@essandess: As you wrote in the homebrew pull request "I personally run the install script on all new boxes I configure/reconfigure, and it’s been bulletproof for me", I understand it is thoroughly tested. Could it be that you run it against a non-standard macOS installation, and/or from a repo/cache/proxy/mirror that does not reflect recent upstream changes (or is simply not fully in sync with this repo), and/or on systems different from standard 10.13.6? Some issues make me think in that direction (gnupg deprecated, ./easylist-pac-privoxy/ empty, no squid.conf.default).

But why python and squid (and maybe privoxy) required manual `port install …` is unclear to me. My system may be not so clean after all...

[*] 
- macOS 10.13.6. Was a 10.13.x test installation (with network, printer, and computer settings via Migration Assistant from my production installation, but not Applications, Users, Other files) updated with the Install Mac OS app
- Xcode 9.4.1 and latest command line tools
- MacPorts base version 2.5.3 via installer .pkg
- minimal drivers and some UI enhancements

---
FWIW, here are the fixes, maybe saving someone some headache.

---
At first run, a prompt to run `xcode-select --install`
=> did so

> "xcode-select: error: command line tools are already installed, use "Software Update" to install updates"

Only at first run, so maybe xcode needed something to register first?

---
> '/Users/test/.local/bin' is not on your PATH.
>     For best results, please add it to the beginning of PATH in your profile.

=> Done. Maybe not necessary?

---
> Error: gnupg has been deprecated. If you absolutely want to stay on the classic version, install the gnupg1 port. All other users are recommended to install gnupg2.

=> `sudo port install gnupg2`
Error remains in later runs of the install script, but later in the script gpg actions are done OK => ignored hereafter.

---

> Selecting 'python36' for 'python3' failed: The specified group 'python3' does not exist.

=> No Python? -- Test:
`port installed python`, `port installed python3`, `port installed python36`, all return 

> None of the specified ports are installed.

`python --version`

> Python 2.7.10

Only the standard Apple version. Specified python was not installed by install script. Reason unclear.
=> `sudo port install python36`, `sudo port select --set python python36`, `sudo port select --set python3 python36`

---

> rsync: link_stat "/Users/test/Desktop/macOS-Fortress-master-port-essandess-2018-07-20/easylist-pac-privoxy/adblock2privoxy/adblock2privoxy*" failed: No such file or directory (2)

./easylist-pac-privoxy/ is empty.
=> searched, downloaded and copied adblock2privoxy-master into easylist-pac-privoxy and renamed it to adblock2privoxy

---

> […lots of ghc-related errors and warnings…]

=> ignored for now.

---

> install: /opt/local/etc/squid/squid.conf.default: No such file or directory

=> renamed the existing squid.conf to squid.conf.default.

---

> chown: privoxy: illegal group name

=> set via System preferences and have an additional user home folder -- naaaahh.
=> `sudo port install privoxy` (privoxy @3.0.26) (forgot to test if privoxy had been installed at all)

---

> install: ./easylist-pac-privoxy/easylist_pac.py: No such file or directory

=> searched and download easylist-pac-privoxy and copied its contents (!) except the empty folder (adblock2privoxy) to ./easylist-pac-privoxy/

---
> Error: Failed to load squid: Launchd plist /Library/LaunchDaemons/org.macports.Squid.plist was not found

=> No Squid installed? -- Test:
`port installed squid`, `port installed squid3` both return

> None of the specified ports are installed.

Squid was not installed.  Reason unclear.
=> `sudo port install squid3`
=> maybe remains of pre-existing squid? `port -f activate squid3` to force the activation.

---

> missing header for unified diff at line 3 of patch

Maybe nonconsequential? Next line says:

> patching file /opt/local/etc/squid/squid.conf

---
> /Users/test/Library/LaunchAgents/org.opensource.flashcookiedelete.plist: Service is disabled

????

---
Finally:

> --->  Loading startupitem 'Squid' for squid
> --->  Loading startupitem 'Privoxy' for privoxy

**Comment by essandess** [comment]
Thanks. Comments:

* The `xcode-select` and `xcodebuild` stuff changes over Xcode versions. I believe you must accept the license by hand now.
* Many of the errors appear that they arose from Macports ports not being installed. I added a test to exit with error if these don’t get installed.
* The `ghc` messages are ignorable, unless `adblock2privoxy` doesn’t get built.
* I fixed the upgrade to `gnupg2`.

Please see the latest commit.

**Comment by noyannus** [comment]
Thank you. I am pinched for time right now, but plan to come back to it asap.
