### ISSUE TITLE
Enhancement? Additional host blocking list

### ISSUE THREAD

**Issue by noyannus** [essandess/macOS-Fortress#8]
There is an interesting list of hosts to block at https://github.com/StevenBlack/hosts.
A rough comparison of its basic Unified hosts = (adware + malware) list with hpHosts shows little overlap (barring a really dumb mistake):
hpHosts: 521k unique hosts
Black: 51k unique hosts
In both lists: 9.2k hosts
Adding the feature to merge Black's list would add more protection, and allow even a thematic blocking for fakenews, gambling, porn, social media for those who want this (e.g., the kid's laptop).

**Comment by essandess** [comment]
That looks like a good list, thanks. I wonder how much overlap there is between this and the default ones used in [easylist-pac-privoxy](
https://github.com/essandess/easylist-pac-privoxy#privoxy)?

Appending these directly to the `/etc/hosts-hphosts` file would add redundancy.

**Comment by noyannus** [comment]
StevenBlacks "updateHostsFile.py script, which is Python 2.7 and Python 3-compatible, will generate a unified hosts file based on the sources in the local data/ subfolder" (under ["Generate your own unified hosts file"](https://github.com/StevenBlack/hosts#generate-your-own-unified-hosts-file)). Maybe there is way to incorporate this (or something similar) in fortress.

**Comment by essandess** [comment]
Thank you! This was added a while ago:

https://github.com/macports/macports-ports/blob/2edc767fcd43edc4e6144aaca071adf3779a3581/net/macos-fortress/Portfile#L1026
