### ISSUE TITLE
is "normal" version of this possible ?

### ISSUE THREAD

**Issue by sokoow** [essandess/macOS-Fortress#9]
is there any hope for a linux version of this ? :D

**Comment by essandess** [comment]
Except for the pf-based firewall, a Linux version would be easy to implement—it's all just config files for squid, privoxy, and apached, along with existing bash update scripts.

Also, I don't believe that there's an up-to-date Linux distro of adblock2privoxy, but that's also an easy port.

**Comment by sokoow** [comment]
Well done by the way - we rarely see such a complete system, fair play.

**Comment by essandess** [comment]
Thanks for the interest.
